spring:
  profiles:
    active: local

# local
---
spring:
  profiles: local
  # devtools setting
  devtools:
    livereload:
      enabled: true
    restart:
      enabled: true
  thymeleaf:
    cache: false
  # database
  datasource:
      url: jdbc:mysql://docker.for.mac.localhost:3306/movievideo
      username: root
      password:
  jpa:
    hibernate:
      ddl-auto: none
    database: mysql
    show-sql: true

logging:
  file: logs/app_log.log
  level:
    root: info